#!/bin/sh 

if [ -z "`dpkg -s cron 2>/dev/null | grep 'ok installed'`" ]; then
    apt-get -y install cron
fi
 
crontabs="apt-update" 
 
for crontab in $crontabs; do 
    if [ ! -h "/etc/cron.d/$crontab" ]; then 
        ln -s /usr/local/etc/cron.d/$crontab \
            /etc/cron.d/$crontab 
    fi  
done

