#!/bin/sh

scripts="colors ixon genpasswd"

for script in $scripts; do
    if [ ! -h "/etc/profile.d/$script.sh" ]; then
        ln -s /usr/local/etc/profile.d/$script.sh \
            /etc/profile.d/$script.sh
    fi
done

